name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          mkdir -name project_folder
          unzip raksha-ai.zip -d project_folder || true
          ls -la project_folder

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find and Build with Gradle
        run: |
          # ऑटोमैटिक आपके प्रोजेक्ट के अंदर जाकर gradlew फ़ाइल ढूंढेगा
          GRADLE_DIR=$(find project_folder -name "gradlew" -exec dirname {} \;)
          if [ -z "$GRADLE_DIR" ]; then
            echo "Error: gradlew file not found inside zip structure."
            exit 1
          fi
          cd "$GRADLE_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: raksha-ai-apk
          path: project_folder/**/build/outputs/apk/debug/*.apk
